export const ENDPOINTS = {
  registerAdmin: "/register-admin",
  adminLogin: "/admin-login",
  getAdminData: "/get-admin-data",
  updateAdminData: "/update-admin-data",
  deleteAdmin: "/delete-admin/:adminId",
  registerStudent: "/register-student",
  getStudent: "/get-student:studentId",
  searchStudent: "/search-student",
  getAllStudents: "/get-all-students",
  deleteStudent: "/delete-student/:studentId",
  getLiveClassSessions: "/get-live-class-sessions",
  postClassRecord: "/post-class-record",
  postAttendance: "/post-attendance/:classId",
  getClassRecord: "/get-class-record/:classId",
  getAllClassRecords: "/get-all-class-records",
  updateClassRecord: "/update-class-record/:classId",
  deleteClassRecord: "/delete-class-record/:classId",
  deleteAttendanceRecord: "/delete-attendance/:classId",
} as const;

export const FM = {
  default: "An error occured",
  invalidCredentials: "Authorization token not provided",
  loginSuccess: "Login successful",
  loginFailed: "Failed to login",
  userExist: "User already exist",
  userNotFound: "User not found",
  userRegisterSuccess: "User registered successfully",
  userRegisterFailed: "User register failed",
  adminNotFound: "Admin not found",
  adminUpdateSuccess: "Admin updated successfully",
  adminUpdateError: "Error updating admin",
  studentRegisterSuccess: "Student registered succesfully",
  studentRegisterFailed: "Error registering user",
  invalidQuery: "Invalid query",
  studentRetrievalFailed: "Student retrieval failed",
  studentNotFound: "Student not found",
  studentDeleteSuccess: "Student deleted successfully",
  studentDeleteFailed: "Failed to delete student",
  classRecordNotFound: "Class record not found",
  classRecordCreationFailed: "Error creating class record",
  errorUpdatingClassRecord: "Error updating class record",
  classRecordRetrievalFailed: "Error retrieving class record",
  classRecordDeleteSuccess: "Class record deleted successfully",
  classRecordDeleteFailed: "Error deleting class record",
  liveClassSessionNotFound: "No live class sessions found",
  addingAttendanceFailed: "Error adding attendance",
  mongoDBConnectionFailed: " Failed to connect to MongoDB",
  serverError: "Internal server error",
  noAuthToken: "Authorization token not provided",
} as const;
