export const ENDPOINTS = {
  registerAdmin: "/register-admin",
  adminLogin: "/admin-login",
  getAdminData: "/get-admin-data",
  updateAdminData: "/update-admin-data",
  deleteAdmin: "/delete-admin/:adminId",
  registerStudent: "/register-student",
  getStudent: "/get-student:studentId",
  searchStudent: "/search-student",
  getAllStudents: "/get-all-students",
  deleteStudent: "/delete-student/:studentId",
  getLiveClassSessions: "/get-live-class-sessions",
  postClassRecord: "/post-class-record",
  postAttendance: "/post-attendance/:classId",
  getClassRecord: "/get-class-record/:classId",
  getAllClassRecords: "/get-all-class-records",
  updateClassRecord: "/update-class-record/:classId",
  deleteClassRecord: "/delete-class-record/:classId",
  deleteAttendanceRecord: "/delete-attendance/:classId",
} as const;
